//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Blog
    {
        public Blog()
        {
            this.Blog_Tag = new HashSet<Blog_Tag>();
        }
    
        public int Id { get; set; }
        [DisplayName("Title")]
        public string Name { get; set; }
        public string Contents { get; set; }
        [DisplayName("Author")]
        public int Author_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual ICollection<Blog_Tag> Blog_Tag { get; set; }
        public virtual User User { get; set; }
    }
}
