//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog_Tag
    {
        public int id { get; set; }
        public int blog_id { get; set; }
        public int tag_id { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual Tag_master Tag_master { get; set; }
    }
}
