//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag_master
    {
        public Tag_master()
        {
            this.Blog_Tag = new HashSet<Blog_Tag>();
        }
    
        public int id { get; set; }
        public string tag_name { get; set; }
    
        public virtual ICollection<Blog_Tag> Blog_Tag { get; set; }
    }
}
